on: workflow_dispatch

# run at 10am, 2pm, 6pm PST through the weekend
# on:
#   schedule:
#     - cron: '0 17,21,1 * * SAT,SUN,MON'

name: Test Image load times

jobs:
  test-image-table:
    runs-on: ubuntu-22.04
    env:
      TEST_COUNT: 5
      PAGE_SIZE: 100
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd playwright
          make deps

      - name: Download previous run results
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          ARTIFACT_NAME: test-image-table-files
          ARTIFACT_FILENAME: test-image-table-files.zip
        with:
          script: |
            const script = require('./playwright/src/github-scripts/download-prev-test-image-table-artifact.js')
            await script({github, context, core})

      - name: Run the test
        run: |
          cd playwright
          ./run.sh

      - name: Upload the test result
        uses: actions/upload-artifact@v4
        with:
          name: test-image-table-files
          path: |
            playwright/test-report.json
            playwright/test.har
          retention-days: 30
